// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// import { Inter, Outfit } from "next/font/google";

// const inter = Outfit({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ContentFlow",
//   description: "Generated by create next app",
//   icons: {
//     icon: '/favicon-32x32.png'
//   }
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <head>
//           <link rel="icon" href="/ContentFlow.png" sizes="any" type="image/png" />
//         </head>
//         <body className={inter.className}>{children}</body>
//       </html>
//     </ClerkProvider>
//   );
// }

import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ContentFlow",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/ContentFlow.png" sizes="any" type="image/png" />
        </head>
        <body className={outfit.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
